import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  bool isEn = true;
  Map<String, Object> textsEn = {
    'app_title': 'Animals Kingdom',
    'language': 'English',
    'language2': 'Arabic',
    'language3': 'English',
    'weight': 'Weight',
    'height': 'Height',
    'food': 'Food',
    'live': 'Live',
    'sound': 'Sound',
    'classification': 'Classification',
    'description': 'Description',
    'read_more': 'Read more...',
    'animal-1': [
      'Lion',
      'assets/icons/lion.png',
      'Male 190 kg, Female 130 kg',
      'Male 1.2 m, Female 1.1 m ',
      'Lions are carnivores, which means they are animals that only eat meat',
      'assets/sounds/lion.mp3',
      'Lions are large carnivorous mammals that belong to the family of felines. They have a tawny coat with a long tufted tail. Male lions have a large mane of darker colored fur surrounding its head and neck. Lions are the only cats that have this obvious difference between the males and the females. Lions are found in savannahs, grasslands, dense bush and woodlands. At one time, lions could be found throughout the Middle East, Greece and even in Northern India.Today, only a small population of lions live in India. Most lions can be found in Africa, but their numbers are becoming smaller because of the loss of habitat.',
      'Male 8-10 years, Female 10-15 years',
      'Roar',
      'Very dangerous, Non-pet animals.',
    ],
    'animal-2': [
      'Tiger',
      'assets/icons/tiger.png',
      'Male: 90 – 310 kg , Female: 65 – 180 kg',
      '70 – 120 cm',
      'Tigers eat a variety of prey ranging in size from termites to elephant calves. However, an integral component of their diet are large-bodied prey weighing about 20 kg  or larger such as moose, deer species, pigs, cows, horses, buffalos and goats.',
      'assets/sounds/tiger.mp3',
      'Tigers are usually orange or reddish orange with very bold, uneven black stripes and white areas on the chest, neck, belly and inside of the legs. Their stripes act as camouflage, making it difficult for them to be seen when they are among the trees and shrubs of the jungle. Tigers have very strong teeth and jaws.',
      '8 – 10 years',
      'Roar',
      'Non-pet animal, very dangerous'
    ],
    'animal-3': [
      'Fox',
      'assets/icons/fox.png',
      '3.2 - 9.4 kg',
      '20 - 50 cm',
      'They are expert hunters, catching rabbits, rodents, birds, frogs and earthworms as well as eating carrion. But they aren\'t carnivorous they also eat berries and fruit too.',
      'assets/sounds/fox.mp3',
      'A fox is a small animal that has a large tail and pointy ears. A red fox’s body is orange, with white underbellies, and black legs. A fox’s tail is called a brush, and the white tip of the red fox’s tail is called a tag. foxes come in many shapes, and sizes, depending on the part of the world where they live. Red foxes are the most common of all the foxes and live in many places around the world.',
      '2- 5 years',
      'Bark, Yelp, Simper',
      'Non-pet animal',
    ],
    'animal-4': [
      'Wolf',
      'assets/icons/wolf.png',
      'Male: 30 – 80 kg , Female: 23 – 55 kg',
      '80 – 85 cm',
      'Wolves are carnivores—they prefer to eat large hoofed mammals such as deer, elk, bison, and moose. They also hunt smaller mammals such as beavers, rodents, and hares. Adults can eat 20 pounds of meat in a single meal.',
      'assets/sounds/wolf.mp3',
      'Gray wolves, or timber wolves, are canines with long bushy tails that are often black-tipped. Their coat color is typically a mix of gray and brown with buffy facial markings and undersides, but the color can vary from solid white to brown or black. Gray wolves look somewhat like a large German shepherd. The base colour of the wolf\'s fur is a grey yellow. Black guard hairs are most prominent on the back, the shoulders and the tip of the tail. The wolf\'s belly side is lighter in tone. The base colour of the wolf\'s legs is grey and the front of the forelegs may have a black streak.',
      '8 - 14 years',
      'Howl, Growl, Bay',
      'Non-pet animal',
    ],
    'animal-5': [
      'Elephant',
      'assets/icons/elephant.jpg',
      '2700 - 6000 kg',
      '2.8 - 3.2 m',
      'Elephants eat roots, grasses, fruit, and bark. An adult elephant can consume up to 300 pounds of food in a single day.',
      'assets/sounds/elephant.mp3',
      'Largest living land animal, characterized by its long trunk (elongated upper lip and nose), columnar legs, and huge head with temporal glands and wide, flat ears. Elephants are grayish to brown in colour, and their body hair is sparse and coarse. They are found most often in savannas, grasslands, and forests but occupy a wide range of habitats, including deserts, swamps, and highlands in tropical and subtropical regions of Africa and Asia.',
      '60 - 70 years',
      'Trumpet',
      'Elephants are not and have never been pet like cats or dogs. It\'s not possible for one individual wild animal to become pet within their lifetime.',
    ],
    'animal-6': [
      'Giraffe',
      'assets/icons/giraffe.png',
      '800 kg',
      '4.6 – 6.1 m',
      'Giraffes eat a variety of fresh  leaves  as well as hay, carrots, and low-starch, high-fiber biscuits.',
      'assets/sounds/girrafe.mp3',
      'These tall animals are identified by their long necks, equally long and spindly legs, and spotted coats. Most giraffes have a tan, white or yellow coats that are spotted with brown, square shapes.',
      'Up to 26 years',
      'Bleat',
      'Giraffes aren\'t ideal as pets. They involve a great deal of feeding, so neighbours tend to become a little irate when their carefully-tended trees begin to disappear from the top downwards.',
    ],
    'animal-7': [
      'Monkey',
      'assets/icons/monkey.png',
      '19 – 37 kg',
      '55 – 65 cm',
      'Monkeys are omnivores. This means that they eat meat and plant-based foods. Most monkeys eat nuts, fruits, seeds and flowers. Some monkeys also eat meat in the form of bird\'s eggs, small lizards, insects and spiders.',
      'assets/sounds/monkey.mp3',
      'Monkeys are intelligent, social animals. Most monkeys have a tail, even if it is a short one (e.g. Barbary Macaque). The word "monkey" is a common-language term. It includes two rather different groups of primates. They have hands with thumbs and dull-colored fur (usually). Monkeys can get around by walking on 2 legs or on 4. They may swing from tree to tree or walk on the ground.',
      '25 - 30 years',
      'Chatter',
      'Overall, monkeys are not good pets. Yes, some can be quite sweet for a time. But the reality is monkeys are capable of causing too much harm and need too much care and attention to thrive in a human household.'
    ],
    'animal-8': [
      'Chimpanzee',
      'assets/icons/chimpanzee.png',
      '34 – 60 kg',
      '1.2 m',
      'Chimpanzees eat a wide variety of food. Scientists have recorded about 80 different items chimps eat, including seeds, fruit, leaves, bark, honey, flowers, and insects. This makes up most of their diet. However, chimpanzees also hunt other wildlife, like monkeys or small antelope, for meat.',
      'assets/sounds/chimpanzee.mp3',
      'Chimpanzees are one of our planet’s ‘great apes’, along with gorillas and orangutans. They have long arms that extend below their knees, short legs and black hair covering almost their entire body. Their faces are flat with big eyes, a small nose and a wide mouth. These amazing animals live in the tropical forests and woodland savannahs of West and Central Africa. Today, populations are fragmented, with the largest groups found in Gabon, Democratic Republic of Congo and Cameroon. Did you know the DNA (the material that determines how a living thing will look and function) of chimps and humans is 98.5% the same? That’s how closely related we are! As a result, we share many similar features, such as expressive faces, big toes and hands that can grasp. We also show similar behaviours, and like us chimps laugh when playing, hug to show affection and are able to walk upright.',
      '40 years',
      'Hoots, Pant-hoots, Pant-grunts, Pant-barks, Rough-grunts',
      'Non-pet animals.',
    ],
    'animal-9': [
      'Gorilla',
      'assets/icons/gorilla.png',
      '140 – 210 kg',
      '1.6 m',
      'Gorillas stick to a mainly vegetarian diet, feeding on stems, bamboo shoots and fruits. Western lowland gorillas, however, also have an appetite for termites and ants, and break open termite nests to eat the larvae.',
      'assets/sounds/gorilla.mp3',
      'Gorillas have dark skin and black to brown-grey hair. Males acquire silver-gray saddles across their backs and upper thighs at sexual maturity, earning them the name silverback. This silver-gray area breaks up their overall dark coloration, creating an optical illusion of increased length and larger size. Sociable gorillas are characterized by a high desire to interact with other gorillas, and show high levels of sympathy, affection and gentleness. Those who scored high on proto-agreeableness (similar to human agreeableness) are friendly, emotional stable and content – the “oases” of calm and peace',
      '35 – 40 years',
      'Belches',
      'Although gorilla shares almost 98% of our DNA, they do not make good pets. Gorillas are also very difficult to care for as they require a specialized diet and feed on large quantities of vegetation.',
    ],
    'animal-10': [
      'Bear',
      'assets/icons/bear.png',
      'Polar bear: 450 kg, Giant panda: 70 – 100 kg.',
      'Polar bear: 1.8 – 2.4 m, Giant panda: 60 – 90 cm.',
      'They feed on the roots and sedges,  carcasses of salmon that died the previous fall after spawning. Because food is relatively scarce during spring.',
      'assets/sounds/bear.mp3',
      'Bears are large mammals that eat mostly meat and fish. Many bears also eat plants, bulbs, and insects. The polar bear eats mostly meat and is classified as carnivores, while the panda feeds almost entirely on bamboo and is classified as a herbivore. The six other species of bear eat both plants and animals and are classified as omnivorous. There are only eight living species of bears and they can be found throughout most of the world. Bears have large bodies, stocky legs, a long snout, shaggy hair, paws with claws, and a short tail. Even though bears are big and heavy, they can run very fast and are also good at climbing and swimming. Bears have a large brain and are one of the more intelligent mammals. Bears take a long sleep in the winter similar to hibernation. They will sleep in their dens and a mother bear will also have her cubs in a den. Bear cubs are born in litters of 1 to 3 and usually stay with their mothers for about 3 years. Most bears live alone except when a female has cubs. A mother bear will defend her cubs ferociously if they are threatened. Polar bears and grizzly bears can be dangerous to people, especially when they are sharing a habitat, but for the most part, bears are shy and are easily frightened of humans. Laws have been passed in many areas of the world to protect bears from hunters and the destruction of their habitat.',
      'Bears can live up to 25 years in the wild and 50 in captivity.',
      'Growl',
      'Non-pet animals.',
    ],
    'animal-11': [
      'Deer',
      'assets/icons/deer.png',
      '160 – 180 kg',
      '85 – 150 cm',
      'Grasses, sedges, the leaves and shoots of trees and other woody plants are all on the menu. Fruit and berries are sometimes eaten too, while tree bark is taken when other food is scarce.',
      'assets/sounds/deer.mp3',
      'Deer are lean, long-legged mammals. Their typical coloring ranges from reddish-brown to gray-brown with cream-colored undersides. Male deer may also be identified by their impressive antlers. These large pests stand three feet tall at the shoulder and approximately six feet long from nose to tail.',
      '6 to 14 years',
      'Buck',
      'Deers are a little dumber than your domestic dogs and cats. So you can consider it under cattle and domesticate it alongside goats or bovine.',
    ],
    'animal-12': [
      'Panda',
      'assets/icons/panda.png',
      '70 - 150 kg',
      '60 -90 cm',
      'Pandas subsist almost entirely on bamboo, eating from 26 to 84 pounds per day.',
      'assets/sounds/panda.mp3',
      'Giant pandas have a distinctive black and white coat, with black fur around their eyes and on their ears, muzzle, legs and shoulders. Their thick, wooly coat helps to keep them warm in their cool mountain homes. Adult pandas are about 150cm from nose to rump, with a 10-15cm tail.',
      'Up to 20 years',
      'Bleat',
      'Non-pet animal'
    ],
    'animal-13': [
      'Kangaroo',
      'assets/icons/Kangaroo.png',
      '18 - 100 kg',
      '* tall: 1.5 - 2 m',
      'kangaroos  are herbivorous, eating mainly leaves and grass in the wild. The kangaroos  are fed a base diet of alfalfa hay.',
      'assets/sounds/kangaroo.mp3',
      'All kangaroos have short hair, powerful hind legs, small forelimbs, big feet and a long tail. They have excellent hearing and keen eyesight. Depending on the species, their fur coat can be red, grey or light to dark brown. Their muscular tail is used for balance when hopping, and as another limb when moving about.',
      '6 - 20 years',
      'Chortle',
      'Kangaroos can communicate with humans similar to the way dogs, horses and goats do despite never having been domesticated.'
    ],
    'animal-14': [
      'Koala',
      'assets/icons/koala.png',
      '4 – 15 kg',
      '* Length: 70 - 90 cm',
      'Koalas eat a variety of eucalyptus leaves and a few other related tree species,  species  paperbark and bloodwood trees.',
      'assets/sounds/koala.mp3',
      'Koalas are well-known for their large round head, big furry ears and big black nose. Their fur is usually grey-brown in colour with white fur on the chest, inner arms, ears and bottom. They have no fur on their nose or the palms of their paws. Koalas have poor vision and rely heavily on their other senses',
      '13 – 18 years',
      'Shriek',
      'Non-pet animal'
    ],
    'animal-15': [
      'Turtle',
      'assets/icons/Turtle.png',
      '272 to 680 kg',
      '* Long: 139 to 160 cm',
      'In the wild, turtles eat a variety of things including worms, small insects, snails, and fish. Wild turtles are mainly carnivorous when they are young because their bodies require protein in order to grow. Plus, growing turtles need the vitamins and nutrients that can be found in feeder fish livers.',
      'assets/sounds/turtle.mp3',
      'All turtles have either a round, smooth or spiny shell. Water turtles have a smooth shell with a tapered shape that\'s designed for efficient swimming. The shell is a distinct feature that separates water turtles from land turtles. Snapping turtles occupy land and water environments and act as ambush predators',
      '10 - 80 years',
      'Cluck ',
      'Pet animal'
    ],
    'animal-16': [
      'Zebra',
      'assets/icons/zebra.png',
      '200 - 450 kg',
      '1.3 - 1.9 m',
      'Zebras are herbivores and feed mostly by grazing on grasses, although they also might browse a bit on the leaves and stems of bushes. They graze for many hours each day, using their strong front teeth to clip off the tips of the grass. Their back teeth then crush and grind the food.',
      'assets/sounds/zebra.mp3',
      'Zebras are generally thought to have white coats with black or brown stripes, according to the San Diego Zoo, because the stripes end at their bellies and the inner side of the legs, which are white.Each species of zebra has a different general pattern of stripes.',
      'Up to 20 years',
      'Neigh, Whinny, Nicker',
      'Pet Animal'
    ],
    'animal-17': [
      'Pig',
      'assets/icons/pig.png',
      '75 – 150 kg',
      '55 - 120 cm',
      'Pigs eat just about anything, all kinds of scraps, or leftover food such as bread, other grains, vegetables, and fruits, their growth rates are best maintained when the animals are fed a feed made specifically for pigs.',
      'assets/sounds/pig.mp3',
      'Pigs are stout-bodied, short-legged, omnivorous mammals, with thick skin usually sparsely coated with short bristles.  flat snouts that can move independently of their heads, small eyes and large ears. They are highly intelligent, social animals, and are found all over the world.,Their hooves have two functional and two nonfunctional digits. Domestic North American pigs originated from wild stocks still found in European, Asian, and North African forests.',
      '15 - 20 years',
      'Snort, Grunt, Squeal, Oink',
      'Pet animal',
    ],
    'animal-18': [
      'Peacock',
      'assets/icons/Peacock.png',
      '4 - 6 kg',
      '* Length from bill to tail of 100 to 115 cm',
      'Peafowl are omnivores which means they will eat both vegetation and meat. Wild peacocks eat fruit, berries, grains, ants, flower petals and plants. Captive peafowl will also eat cat food, cheese, nuts, scrambled egg, cooked rice and kitchen scraps.',
      'assets/sounds/Peacock.mp3',
      'Their bodies are covered with brown feathers and an elongated tail with impressive blue and greenish feathers are found on males. A peacock\'s tail makes up 60% of its entire length. The tail has eye-like spots with red, gold, and green feathers surrounding the eyespots.',
      '10 - 25 years',
      'Scream',
      'Peacocks are popular pets with people eager to host the showy ornamental bird.',
    ],
    'animal-19': [
      'Hedgehog',
      'assets/icons/headgehog.png',
      '0.4 - 1.2 kg ',
      '10 to 30 cm',
      'The most important invertebrates in their diet are worms, beetles, slugs, caterpillars, earwigs and millipedes. As well as these, they also eat a wide range of other insects. More infrequently, they will take advantage of carrion, frogs, baby rodents, baby birds, birds\' eggs and fallen fruit.',
      'assets/sounds/hedgehog.mp3',
      'Hedgehogs are small mammals with cone-shaped faces, short legs and bodies that are covered with porcupine-like quills. Hedgehog quills are made from keratin, much like human nails. According to the African Wildlife Foundation (AWF), a hedgehog can have as many 6,000 quills on its body',
      '2 – 5 years',
      'Hissing, Snarling, Purring',
      'Pet hedgehogs are quiet, active, entertaining, and require a lot of care. They make great companion pets, however, as nocturnal animals, you will need to feed and care for them in the evening hours.'
    ],
    'animal-20': [
      'Rabbit',
      'assets/icons/rabbit.png',
      '2 - 4.5 kg',
      '* Length: 20 - 50 cm',
      'Good quality hay or grass, always available, should constitute the majority of rabbits\' diets. Rabbits graze, naturally eating grass and other plants for long periods, mainly at dawn and dusk. Rabbits\' digestive systems need grass or hay to function properly.',
      'assets/sounds/rabbit.mp3',
      'Rabbits are small, furry mammals with , and long ears, short fluffy tails, and strong, large hind legs. They have 2 pairs of sharp incisors (front teeth), one pair on top and one pair on the bottom. They also have 2 peg teeth behind the top incisors.',
      'There are more than 30 species around the world, and while they live in many different environments, they have many things in common. Rabbits and hares are in the same taxonomic family, Leporidae, but they are in different genera.',
      'Can easily live to be 8 years old',
      'Squeak',
      'Pet and beautiful animal'
    ],
    'animal-21': [
      'Horse',
      'assets/icons/horse.png',
      '380 – 1,000 kg',
      '1.4 – 1.8 m',
      'Horses eat grass and hay or haylage, but salt, concentrates and fruits or vegetables can also enhance their diets, depending on the required work regime and available feed.',
      'assets/sounds/horse.mp3',
      'Horses have oval-shaped hooves, long tails, short hair, long slender legs, muscular and deep torso build, long thick necks, and large elongated heads. The mane is a region of coarse hairs, which extends along the dorsal side of the neck in both domestic and wild species.Horses can display traits that qualify them as social, aloof, fearful, and challenging. Further, as well as noting specific temperament traits that match your equine the best, you also need to notice how “loudly” or “quietly” (“aggressively” or “passively”)  horse displays his personality.',
      '25 – 30 years',
      'Whinny',
      'Pet animal',
    ],
    'animal-22': [
      'Camel',
      'assets/icons/camel.png',
      '400 - 600 kg',
      '1.8 - 2 m',
      'In the desert, people feed camels with grass, grains, wheat and oats. When camels are travelling in the desert, food is often very hard to find. So the animal might have to live on dried leaves, seeds, and thorny twigs (without hurting their mouths).',
      'assets/sounds/camel.mp3',
      'Long legs and a small head make the camel appear oddly formed. Its gait also seems awkward as the front and back legs on the same side move forward together, creating a rocking motion. Camels have either one hump (Dromedary) or two humps (Bactrian).',
      'up to 40 years',
      'Grunt',
      'Pet animal'
    ],
    'animal-23': [
      'Dog',
      'assets/icons/jermandog.png',
      '30 - 40 kg',
      '15 - 110 cm',
      'Dry food',
      'assets/sounds/dog.mp3',
      'Dogs are domesticated mammals, not natural wild animals. They were originally bred from wolves. They have been bred by humans for a long time, and were the first animals ever to be domesticated. They are a popular pet because they are usually playful, friendly, loyal and listen to humans. Dogs are sometimes referred to as man\'s best friend because they are kept as domestic pets and are usually loyal and like being around humans. Dogs like to be petted, but only when they can first see the petter\'s hand before petting one should never pet a dog from behind.',
      '10 -13 years',
      'Bark',
      'Pet animals, Best friend to the Human',
    ],
    'animal-24': [
      'Cat',
      'assets/icons/cat.png',
      '3.6 – 4.5 kg',
      '23 – 25 cm ',
      'Cats are meat eaters, plain and simple. They have to have protein from meat for a strong heart, good vision, and a healthy reproductive system. Cooked beef, chicken, turkey, and small amounts of lean deli meats are a great way to give them that. Raw or spoiled meat could make your cat sick.',
      'assets/sounds/cat.mp3',
      'A cat is a furry animal that has a long tail and sharp claws. Cats are often kept as pets. Cats are lions, tigers, and other wild animals in the same family.',
      '2 - 16 years',
      'Meows',
      'Pet animals.',
    ],
    'animal-25': [
      'Hippopotamus',
      'assets/icons/Hippopotamus.png',
      'Male: 1,500 – 1,800 kg, Female: 1,300 – 1,500 kg',
      '1.5 m',
      'They spend four to five hours grazing and can consume 68 kg  of grass each night. Like most herbivores, hippos consume other plants if presented with them, but their diet in nature consists almost entirely of grass, with only minimal consumption of aquatic plants.',
      'assets/sounds/hippo.mp3',
      'Hippos are large semi-aquatic mammals, with a large barrel-shaped body, short legs, a short tail and an enormous head! They have greyish to muddy-brown skin, which fades to a pale pink colour underneath.  These magnificent mammals were once found throughout all sub-saharan Africa.',
      '40 - 50 years',
      'Growl',
      'Hippos are aggressive and are considered very dangerous. They have large teeth and tusks that they use for fighting off threats, including humans. Sometimes, their young fall victim to adult hippos\' tempers. During a fight between two adults, a young hippo caught in the middle can be seriously hurt or even crushed.'
    ],
    'animal-26': [
      'Oxen',
      'assets/icons/ox.png',
      '350 - 1100 kg',
      '1.2 m',
      'Oxen are herbivores, meaning that they eat a diet of plants and grains. Domesticated oxen eat fresh grasses as well as hay and grain supplements.',
      'assets/sounds/oxen.mp3',
      'Musk ox are dark brown or black. They have long, coarse outer hair which makes them look a bit like a buffalo but they are actually more similar to sheep.',
      '18 – 22 years',
      'Bellow',
      'Non-pit animal'
    ],
    'animal-27': [
      'Buffalo',
      'assets/icons/bufflo.png',
      '425–870 kg',
      '1 - 1.7 m ',
      'Buffalo are herbivores, and so eat only vegetation. Their favorite foods are grass and herbs, but water buffalo will also eat aquatic plants. Both African and Asian buffalo will eat shrubs and trees when they can\'t find grass or herbs to eat.',
      'assets/sounds/buffalo.mp3',
      'Buffalo can be 6 to 7 feet long, stand from 5 to 6 feet tall and weigh up to 2,000 pounds. Their size makes them the largest animal living in North America. ... Buffalo are herbivores and feed on about 60 pounds of plant material and grasses a day. Buffalo are considered to be an adult when they reach 3 years old.',
      'Up to 26 years',
      'Grunts',
      'Pet animals.',
    ],
    'animal-28': [
      'Sheep',
      'assets/icons/Sheep.png',
      '45 – 160 kg',
      '85 – 140 cm',
      'Sheep are herbivores and eat mainly plant material. In the wild or when living in pastures, sheep spend a good part of their day grazing on grass and weeds. Sheep that live in an enclosure with no grass to graze are often fed hay or silage or corn.',
      'assets/sounds/sheep.mp3',
      'Sheep are four legged artiodactyla or even toed (they have two toes on each toe) mammals. Sheep are covered almost completely in wool. Wool is a soft curly hair used for fiber, and is very irritating to the skin when in sweater form. Sheeps have  horns forming a lateral spiral .  Another trait unique to sheep are their wide variation in colour.',
      '10 – 12 years',
      'Bleat',
      'Pet animal',
    ],
    'animal-29': [
      'Goat',
      'assets/icons/goat.png',
      '20 – 140 kg',
      '41 – 58 cm',
      '90% of the food they eat is pasture or hay. Undebatably this is the most favorite. In general, goats love to eat pasture, raisins, greens, chaffhaye, sunflower seeds, carrots, pumpkin seeds.',
      'assets/sounds/goat.mp3',
      'Goat, from hollow-horned mammal belonging to the genus Capra. Related to the sheep, the goat is lighter of build, has horns that arch backward, a short tail, and straighter hair. Male goats, called bucks or billys, usually have a beard. Females are called does or nannys, and immature goats are called kids. Wild goats include the ibex and markhor.',
      '15 – 18 years',
      'Bleat',
      'Pet animal',
    ],
    'animal-30': [
      'Duck',
      'assets/icons/duck.png',
      '1 - 8 kg',
      '10 - 60 cm ',
      'Alfalfa meal (high protein, good for winter), Corn (a mainstay for chickens, store whole), Field peas (for protein, to avoid soybean use), Wheat, Oats and/or barley (less than 15 percent of the total diet together)',
      'assets/sounds/duch.mp3',
      'Ducks are mostly aquatic birds, mostly smaller than the swans and geese, and may be found in both fresh water and sea water. Ducks are sometimes confused with several types of unrelated water birds with similar forms, such as loons or divers, grebes, gallinules and coots.',
      '2 - 10 years',
      'Quack',
      'Pet animals.',
    ],
    'animal-31': [
      'Chicken',
      'assets/icons/chicken.png',
      '1 - 5 kg',
      '10 - 40 cm ',
      'Alfalfa meal (high protein, good for winter), Corn (a mainstay for chickens, store whole), Field peas (for protein, to avoid soybean use), Wheat, Oats and/or barley (less than 15 percent of the total diet together)',
      'assets/sounds/chichen.mp3',
      'A chicken is a bird. One of the features that differentiate it from most other birds is that it has a comb and two wattles. The comb is the red appendage on the top of the head, and the wattles are the two appendages under the chin. These are secondary sexual characteristics and are more prominent in the male. A few other birds have a comb or similar appendage, in some cases bearing a different name such as helmet in the guinea, and a few have wattles with some having a single median one rather than a pair.',
      '2 - 10 years',
      'Cluck, Cackle',
      'Pet animals.',
    ],
    'animal-32': [
      'Frog',
      'assets/icons/frog.png',
      '22.7 g',
      '* long: 4.2 - 15 cm',
      'Small frogs eat insects such as flies and moths, as well as snails, slugs and worms. They use long tongues and sticky saliva to catch prey that passes them by. tadpoles eat algae in the ponds they grow in. As they grow, they feed on plants and small insects. If there isn\'t enough food available they might even eat their fellow tadpoles.',
      'assets/sounds/frog.mp3',
      'Frogs are amphibians that are known for their jumping abilities, croaking sounds, bulging eyes and slimy skin. They live all over the world and are among the most diverse animals in the world, with more than 6,000 species. frogs substantially outnumber the two other groups of amphibians — salamanders and caecilians.',
      '10 – 12 years',
      'Ribbit',
      'Frogs are not a pet that should be handled regularly due to their special, sensitive skin.',
    ],
    'animal-33': [
      'Parrot',
      'assets/icons/parrot.png',
      '64 g to 1.6 kg',
      '8.7 to 100 centimeters',
      'The best foods for your pet parrot to eat are fresh vegetables, fruit and pellets or seeds. In the wild, parrot\'s diet can vary considerably and they like to eat fruit and fruit seeds, nuts, flowers, and corn where they can find it.',
      'assets/sounds/parrot.mp3',
      ' Parrots have a heavy, in relation to their size, and compact body with a large head and a short neck. Their beaks are short, strong and curved. The two parts of the beak are very strong and used to break fruits and seeds. Many parrots are vividly coloured, and some are multi-coloured.they have four toes on each foot, two pointing forward and two projecting backward. Most parrots eat fruit, flowers, buds, nuts, seeds.',
      '40 - 80 years',
      'Talk, Screech, Squawk',
      'Pet and beautiful bird'
    ],
    'animal-34': [
      'Butterfly',
      'assets/icons/butterfly.png',
      'less than 1 g',
      '* length 2 - 10 cm',
      ' Most  butterflies drink nectar from flowers through their tongues, which function much like straws. A minority of butterflies almost never visits flowers, instead gaining sustenance from tree sap, rotting animal matter, and other organic material.',
      'assets/sounds/butterfly.mp3',
      'The adult butterfly has four wings that are covered with tiny scales that give them their colorful and diverse designs. They have six legs, two antenna, a head, compound eyes, a thorax, and an abdomen. Butterflies also have fairly good eye sight.',
      'Up to 12 months',
      'Loud cracking',
      'Pet bird, very beautiful'
    ],
    'animal-35': [
      'Eagle',
      'assets/icons/eagle.png',
      '3 – 6.3 kg',
      'The adult male is about 90 cm long and has a wingspan of 2 metres Females, which grow somewhat larger than males, may reach 108 cm in length and have a wingspan of 2.5 metres. Both sexes are dark brown, with a white head and tail.',
      'Main live prey consists of medium sized mammals and birds such as rabbits.',
      'assets/sounds/eagle.mp3',
      'Eagles are large, powerfully built birds of prey, with heavy heads and beaks. Like all birds of prey, eagles have very large hooked beaks for ripping flesh from their prey, strong, muscular legs, and powerful talons. The beak is typically heavier than that of most other birds of prey.',
      '20 - 31 years',
      'Scream',
      'Eagles can be domesticated. However, there are certain types of eagles can be trained, as the Golden Eagle. Out of all the animals the humankind has domesticated in history, Golden Eagles might be the wildest and most exciting species of all.'
    ],
    'animal-36': [
      'Pigeon',
      'assets/icons/Pigeon.png',
      '240 – 380 g',
      '25cm-30cm',
      'The pigeons that dominate our cities and urban environments will eat almost anything, from insects to leftover food we throw out. Wild pigeons will eat whatever nature throws their way. Again, this includes insects such as worms and ants, as well as seeds, fruits, berries and vegetables.',
      'assets/sounds/pigeons.mp3',
      'Dark bluish-grey head, neck and chest with glossy greenish and reddish-purple iridescence around the neck and wing feathers. 2 black bars in the wing, and blue-gray head. Plump bird with short legs and small head. Plumage is variable. some birds are dark gray with green-purple iridescence on the neck. Orange or red iris with pale inner ring (adult) or brown or greyish brown (juveniles) Black bill with off-white cere. Red feet and legs.',
      '2 - 3 years',
      'Coo',
      'Pet Bird',
    ],
    'animal-37': [
      'Crow',
      'assets/icons/crow.png',
      '337 - 1,625 g',
      '45 - 48 cm',
      'Crows are omnivores, which means they eat nearly anything. Crows eat small animals such as mammals, amphibians, reptiles, eggs and carrion. They also eat insects, seeds, grains, nuts, fruit, non-insect arthropods, mollusks, worms and even other birds.',
      'assets/sounds/crow.mp3',
      'Crows are large birds with long legs and heavy, straight bills. These birds are entirely black in color, including their legs and feet. They have distinct feathers on their upper backs with an opalescent quality, which is especially apparent in the sunlight.',
      '7 - 15',
      'Caw',
      'Non-pet Bird',
    ],
    'animal-38': [
      'Bee',
      'assets/icons/bee.png',
      '0.8 g',
      '18 mm',
      'most bees use pollen and nectar as a food source.',
      'assets/sounds/bee.mp3',
      'Bees have a long, straw-like tongue called a probiscus that allows them to drink the nectar from deep within blossoms. Bees are also equipped with two wings, two antennae, and three segmented body parts (the head, the thorax, and the abdomen).  Honeybees are social insects that live in colonies.',
      'During the active season, the lifetime of a worker is five to six weeks. Overwintering worker bees may, however, live for four to six months.',
      'Hum and Buzz',
      'Non-pet bee.',
    ],
    'animal-39': [
      'Owl',
      'assets/icons/owl.png',
      'Nearly 4.5 kg',
      '43 to 64 cm',
      'Owls eat other animals, from small insects such as moths or beetles, to large birds, even as large as an Osprey. A few species of owls mostly eat fish, such as Ketupa (fish-owl) and Scotopelia (fishing-owl) species, found in Asia and Sub-Saharan Africa, respectively.',
      'assets/sounds/owl.mp3',
      'Whether large or small, they all look stocky with large heads and soft feathers. The colors of owl feathers tend to be tan, brown, gray, rufous, and white. These muted tones help owls camouflage themselves against tree trunks and branches. Unlike most raptors, many owls have feathers on their legs and toes.',
      '20-25 years',
      'Hooting',
      'Non-pet Bird',
    ],
    'animal-40': [
      'Snake',
      'assets/icons/snake.png',
      '1 - 75 kg',
      '* Tall : 0.3 - 15 m',
      'All snakes are carnivores. Their diet depends on the species. Some eat warm-blooded prey (e.g., rodents, rabbits, birds), while others eat insects, amphibians (frogs or toads), eggs, other reptiles, fish, earthworms, or slugs. Snakes swallow their food whole.',
      'assets/sounds/snake.mp3',
      'A snake is a reptile with a long, thin body but no legs. Some lizards are legless and look like snakes, however, most lizards have eyelids, and snakes do not. A snake\'s jaws are flexible and can open very wide, so snakes can tackle big prey.   more than 3,400 species of reptiles distinguished by their limbless condition and greatly elongated body and tail. All snakes lack external limbs.',
      '9 - 30 years',
      'Hiss, Rattle',
      'Very dangerous, non-pet animal',
    ],
  };
  Map<String, Object> textsAr = {
    'app_title': 'مملكة الحيوانات',
    'language': 'عربي',
    'language2': 'عربي',
    'language3': 'إنجليزي',
    'read_more': 'إقرأ المزيد...',
    'weight': 'الوزن',
    'height': 'الطول',
    'food': 'الطعام',
    'live': 'فترة حياته',
    'sound': 'الصوت',
    'classification': 'التصنيف',
    'description': 'الوصف',
    'animal-1': [
      'الأسد',
      'assets/icons/lion.png',
      'الذكر 190 كجم والأنثي 130 كجم',
      'الذكر 1.2 م والأنثى 1.1 م',
      'الأسود من الحيوانات آكلة اللحوم ، مما يعني أنها حيوانات تأكل اللحوم فقط',
      'assets/sounds/lion.mp3',
      'الأسود هي ثدييات كبيرة آكلة للحوم تنتمي إلى عائلة الماكرون. لديهم معطف أسمر مع ذيل طويل معنقدة. ذكور الأسود لها بدة كبيرة من الفراء ذات اللون الغامق تحيط برأسها وعنقها. الأسود هي القطط الوحيدة التي لديها هذا الاختلاف الواضح بين الذكور والإناث. تم العثور على الأسود في السافانا والمراعي والأدغال الكثيفة والغابات. في وقت ما ، كان من الممكن العثور على الأسود في جميع أنحاء الشرق الأوسط واليونان وحتى في شمال الهند ، واليوم ، يعيش عدد قليل فقط من الأسود في الهند. يمكن العثور على معظم الأسود في إفريقيا ، لكن أعدادها أصبحت أقل بسبب فقدان موطنها.',
      'الذكور 8-10 سنوات والاناث 10-15 سنة',
      'زئير',
      'حيوان غير أليف، خطير للغاية',
    ],
    'animal-2': [
      'النمر',
      'assets/icons/tiger.png',
      'الذكر: 90 - 310 كجم، الأنثي:65 - 180 كجم',
      '70 - 120 سم',
      'يأكل النمور مجموعة متنوعة من الفرائس تتراوح في الحجم من النمل الأبيض إلى عجول الفيل. ومع ذلك ، فإن جزءًا لا يتجزأ من نظامهم الغذائي هو الفريسة ذات الجسم الكبير التي تزن حوالي 20 كجم أو أكبر مثل الموظ وأنواع الغزلان والخنازير والأبقار والخيول والجاموس والماعز.',
      'assets/sounds/tiger.mp3',
      'عادة ما تكون النمور برتقالية أو برتقالية ضاربة إلى الحمرة مع خطوط سوداء جريئة للغاية ومناطق بيضاء على الصدر والرقبة والبطن وداخل الساقين. تعمل خطوطهم كتمويه ، مما يجعل من الصعب عليهم رؤيتهم عندما يكونون بين الأشجار والشجيرات في الغابة. النمور لديها أسنان وفكين قويان جدا.',
      '8 - 10 سنوات',
      'زئير',
      'خطير للغاية، حيوان غير أليف'
    ],
    'animal-3': [
      'الثعلب',
      'assets/icons/fox.png',
      '3.2 - 9.4 كجم ',
      '20 - 5- سم',
      'هم صيادون محترفون ، يصطادون الأرانب ، القوارض ، الطيور ، الضفادع وديدان الأرض وكذلك يأكلون الجيف كما يأكلون التوت والفواكه أيضًا.',
      'assets/sounds/fox.mp3',
      'الثعلب حيوان صغير له ذيل كبير وأذنان مدببتان. جسد الثعلب الأحمر برتقالي اللون ، وبه ثنيات بيضاء ، وأرجل سوداء. يسمى ذيل الثعلب بالفرشاة ، ويطلق على الطرف الأبيض من ذيل الثعلب الأحمر علامة. تأتي الثعالب بأشكال وأحجام عديدة ، اعتمادًا على الجزء الذي تعيش فيه من العالم. الثعالب الحمراء هي الأكثر شيوعًا بين جميع الثعالب وتعيش في العديد من الأماكن حول العالم.',
      '2- 5 سنوات',
      'ضُباح',
      'حيوان غير أليف',
    ],
    'animal-4': [
      'الذئب',
      'assets/icons/wolf.png',
      'ذكور: 30 -80  كجم أنثى: 23 - 55 كجم',
      '80 - 85 سم',
      'تعتبر الذئاب من الحيوانات آكلة اللحوم - فهي تفضل أكل الثدييات ذات الحوافر الكبيرة مثل الغزلان والأيائل والبيسون والموظ. كما أنهم يصطادون الثدييات الأصغر مثل القنادس والقوارض والأرانب البرية. يمكن للبالغين تناول 20 رطلاً من اللحم في وجبة واحدة.',
      'assets/sounds/wolf.mp3',
      'الذئاب الرمادية ، أو ذئاب الأخشاب ، هي ذئاب ذات ذيول كثيفة طويلة غالبًا ما تكون ذات رؤوس سوداء. عادة ما يكون لون معطفهم مزيجًا من الرمادي والبني مع علامات وجه مصفرة وجوانب سفلية ، ولكن يمكن أن يختلف اللون من الأبيض الصلب إلى البني أو الأسود. اللون الأساسي لفراء الذئب أصفر رمادي. يظهر شعر الحارس الأسود بشكل بارز على الظهر والكتفين وطرف الذيل. جانب بطن الذئب أخف في النغمة. اللون الأساسي لساقي الذئب رمادي وقد يحتوي الجزء الأمامي من الأرجل على خط أسود.',
      '8 - 14 عاماً',
      'عواء',
      'حيوان غير أليف',
    ],
    'animal-5': [
      'الفيل',
      'assets/icons/elephant.jpg',
      '2700 - 6000 كجم',
      '2.8 - 3.2 م',
      'تأكل الفيلة الجذور والأعشاب والفاكهة واللحاء. يمكن للفيل البالغ أن يستهلك ما يصل إلى 300 رطل من الطعام في اليوم الواحد.',
      'assets/sounds/elephant.mp3',
      'أكبر حيوان بري ، يتميز بجذعه الطويل (شفته العليا وأنفه الممدودان) ، وأرجله العمودية ، ورأسه الضخم مع غدد صدغية وآذان عريضة ومسطحة. الفيلة رمادية إلى بنية اللون ، وشعر أجسامها متناثر وخشن. توجد غالبًا في السافانا والأراضي العشبية والغابات ولكنها تحتل مجموعة واسعة من الموائل ، بما في ذلك الصحاري والمستنقعات والمرتفعات في المناطق الاستوائية وشبه الاستوائية في إفريقيا وآسيا.',
      '60 - 70 عاماً',
      'بوق، نهيم',
      'الفيلة ليست حيوانات أليفة مثل القطط والكلاب ولم تكن أبدًا حيوانات أليفة. ليس من الممكن أن يصبح حيوان بري واحد حيوانًا أليفًا خلال حياته.',
    ],
    'animal-6': [
      'الزرافة',
      'assets/icons/giraffe.png',
      '800 كجم',
      '4.6 - 6.1 م',
      'تأكل الزرافات مجموعة متنوعة من الأوراق الطازجة بالإضافة إلى التبن والجزر والبسكويت عالي النشا والغني بالألياف.',
      'assets/sounds/girrafe.mp3',
      'يتم التعرف على هذه الحيوانات الطويلة من خلال رقابها الطويلة وأرجلها الطويلة والمغزلية والمعاطف المرقطة. تحتوي معظم الزرافات على معاطف تان أو بيضاء أو صفراء مرقطة بأشكال مربعة بنية اللون.',
      'تصل إلى 26 عام',
      'الطنين',
      'الزرافات ليست مثالية كالحيوانات الأليفة. إنها تنطوي على قدر كبير من التغذية ، لذلك يميل الجيران إلى الشعور بالغضب قليلاً عندما تبدأ أشجارهم التي تم الاعتناء بها بعناية في الاختفاء من أعلى إلى أسفل.',
    ],
    'animal-7': [
      'القرد',
      'assets/icons/monkey.png',
      '19 - 37 كجم',
      '55 - 65 سم',
      'القرود حيوانات آكلة اللحوم. هذا يعني أنهم يأكلون اللحوم والأطعمة النباتية. معظم القرود تأكل المكسرات والفواكه والبذور والزهور. كما تأكل بعض القرود اللحوم على شكل بيض الطيور والسحالي الصغيرة والحشرات والعناكب.',
      'assets/sounds/monkey.mp3',
      'القرود حيوانات اجتماعية ذكية. معظم القرود لها ذيل ، حتى لو كان قصيرًا (مثل المكاك البربري). كلمة "قرد" مصطلح شائع اللغة. وهي تضم مجموعتين مختلفتين من الرئيسيات. لديهم أيدي مع الإبهام وفراء باهت اللون (عادة). يمكن للقرود أن تتجول بالمشي على قدمين أو على 4. وقد تتأرجح من شجرة إلى أخرى أو تمشي على الأرض.',
      '25 - 30 عاماً',
      'ضحك',
      'بشكل عام ، القردة ليست حيوانات أليفة جيدة. نعم ، يمكن أن يكون البعض حلوًا لبعض الوقت. لكن الحقيقة هي أن القردة قادرة على التسبب في الكثير من الضرر وتحتاج إلى الكثير من العناية والاهتمام لتزدهر في منزل بشري.',
    ],
    'animal-8': [
      'الشمبانزي',
      'assets/icons/chimpanzee.png',
      '34 - 60 كجم',
      '1.2 م',
      'يأكل الشمبانزي مجموعة متنوعة من الأطعمة. سجل العلماء حوالي 80 عنصرًا مختلفًا يأكلها الشمبانزي ، بما في ذلك البذور والفاكهة والأوراق واللحاء والعسل والزهور والحشرات. هذا يشكل معظم نظامهم الغذائي. ومع ذلك ، فإن الشمبانزي يصطاد أيضًا حيوانات برية أخرى ، مثل القرود أو الظباء الصغيرة ، من أجل اللحوم.',
      'assets/sounds/chimpanzee.mp3',
      'الشمبانزي هو أحد "القردة العظيمة" على كوكبنا ، إلى جانب الغوريلا وإنسان الغاب. لديهم أذرع طويلة تمتد تحت الركبتين وأرجل قصيرة وشعر أسود يغطي أجسامهم بالكامل تقريبًا. وجوههم مسطحة وعيون كبيرة وأنف صغير وفم واسع. تعيش هذه الحيوانات المدهشة في الغابات الاستوائية وغابات السافانا في غرب ووسط إفريقيا. اليوم ، السكان مجزأون ، مع وجود أكبر المجموعات في الجابون وجمهورية الكونغو الديمقراطية والكاميرون. هل تعلم أن الحمض النووي (المادة التي تحدد كيف سيبدو الكائن الحي ويعمل) للشمبانزي والبشر هو 98.5٪ متماثل؟ هذا هو مدى ارتباطنا الوثيق! نتيجة لذلك ، نتشارك العديد من الميزات المتشابهة ، مثل الوجوه المعبرة وأصابع القدم الكبيرة واليدين التي يمكنها الإمساك. نظهر أيضًا سلوكيات مماثلة ، ومثلما نضحك الشمبانزي عندما نلعب ، نعانق لإظهار المودة وتكون قادرة على المشي منتصبة.',
      '40 عام',
      'ناهيت',
      'حيوان غير أليف',
    ],
    'animal-9': [
      'الغوريلا',
      'assets/icons/gorilla.png',
      '140 - 210 كجم',
      '1.6 م',
      'تلتزم الغوريلا بنظام غذائي نباتي بشكل أساسي ، وتتغذى على السيقان وبراعم الخيزران والفواكه. ومع ذلك ، فإن غوريلا السهول الغربية لديها أيضًا شهية للنمل الأبيض والنمل ، وتفتح أعشاش النمل الأبيض لأكل اليرقات.',
      'assets/sounds/gorilla.mp3',
      'الغوريلا لها بشرة داكنة وشعر أسود إلى بني رمادي. يكتسب الذكور سروجًا فضية رمادية عبر ظهورهم وأعلى أفخاذهم عند النضج الجنسي ، هذه المنطقة الرمادية الفضية تكسر لونهم الغامق العام ، مما يخلق وهمًا بصريًا بزيادة الطول والحجم الأكبر. تتميز الغوريلا المؤنسة برغبة كبيرة في التفاعل مع الغوريلا الأخرى ، وتظهر مستويات عالية من التعاطف والمودة والوداعة. أولئك الذين سجلوا درجات عالية في التوافق البدائي (على غرار التوافق البشري) هم ودودون ومستقرون عاطفيًا ومحتوى - "واحات" الهدوء والسلام.',
      '35 - 40 عامااً',
      'ناهيت',
      'على الرغم من أن الغوريلا تشارك ما يقرب من 98٪ من حمضنا النووي ، إلا أنها حيوانات غير أليفة. يصعب أيضًا العناية بالغوريلا لأنها تتطلب نظامًا غذائيًا متخصصًا وتتغذى على كميات كبيرة من النباتات.',
    ],
    'animal-10': [
      'الدب',
      'assets/icons/bear.png',
      'الدب القطبي: 450 كجم ، الباندا العملاقة: 70-100 كجم.',
      'الدب القطبي: 1.8 - 2.4 م ، الباندا العملاقة: 60-90 سم.',
      'تتغذى على الجذور والرواسب ، جثث السلمون التي ماتت في الخريف السابق بعد التفريخ. لأن الطعام نادر نسبيًا خلال فصل الربيع.',
      'assets/sounds/bear.mp3',
      'الدببة من الثدييات الكبيرة التي تأكل اللحوم والأسماك في الغالب. تأكل العديد من الدببة أيضًا النباتات والمصابيح والحشرات. يأكل الدب القطبي اللحوم في الغالب ويصنف على أنه آكلات اللحوم ، بينما يتغذى الباندا بالكامل تقريبًا على الخيزران ويصنف على أنه من الحيوانات العاشبة. الأنواع الستة الأخرى من الدب تأكل النباتات والحيوانات وتصنف على أنها آكلة اللحوم. لا يوجد سوى ثمانية أنواع حية من الدببة ويمكن العثور عليها في معظم أنحاء العالم. للدببة أجسام كبيرة وأرجل ممتلئة وخطم طويل وشعر أشعث وأقدام لها مخالب وذيل قصير. على الرغم من أن الدببة كبيرة وثقيلة ، إلا أنها تستطيع الركض بسرعة كبيرة وهي جيدة أيضًا في التسلق والسباحة. تمتلك الدببة دماغًا كبيرًا وهي واحدة من أكثر الثدييات ذكاءً. تأخذ الدببة نومًا طويلًا في الشتاء يشبه السبات. سوف ينامون في أوكارهم ، كما ستضع أم الدب أشبالها في عرين. يولد أشبال الدب في مواليد من 1 إلى 3 ويبقون عادة مع أمهاتهم لمدة 3 سنوات. تعيش معظم الدببة بمفردها إلا عندما يكون لدى الأنثى صغار. ستدافع أم الدب عن أشبالها بشراسة إذا تعرضت للتهديد. يمكن أن تكون الدببة القطبية والدببة الرمادية خطرة على الناس ، خاصةً عندما يتشاركون موطنًا لهم ، ولكن بالنسبة للجزء الأكبر ، تكون الدببة خجولة ويسهل إخافتها من البشر. تم تمرير قوانين في العديد من مناطق العالم لحماية الدببة من الصيادين وتدمير بيئتها.',
      'يمكن أن تعيش الدببة حتى 25 عامًا في البرية و 50 عامًا في الأسر.',
      'قَهْقَاع',
      'حيوان غير أليف',
    ],
    'animal-11': [
      'الغزال',
      'assets/icons/deer.png',
      '160 - 180 كجم',
      '85 - 150 سم',
      'الحشائش وأوراق وبراعم الأشجار والنباتات الخشبية الأخرى. يأكلون الفاكهة والتوت أحيانًا ، بينما يؤخذ لحاء الأشجار عندما يندر الطعام الآخر.',
      'assets/sounds/deer.mp3',
      'الغزلان هي ثدييات هزيلة وذات أرجل طويلة. يتراوح لونها النموذجي من البني المحمر إلى البني الرمادي مع الجوانب السفلية ذات اللون الكريمي. يمكن أيضًا التعرف على ذكر الغزلان من خلال قرونهم المثيرة للإعجاب. تقف هذه القرون الكبيرة بطول ثلاثة أقدام عند الكتف وطولها ستة أقدام تقريبًا من الأنف إلى الذيل.',
      '6 - 14 عامااً',
      'سليل',
      'الغزلان أغبى قليلاً من القطط والكلاب الأليفة. لذلك يمكنك اعتباره تحت الماشية والاحتفاظ به جنبًا إلى جنب مع الماعز أو الأبقار.',
    ],
    'animal-12': [
      'الباندا',
      'assets/icons/panda.png',
      '70 - 150 كجم',
      '60 - 90 سم',
      'تعيش الباندا بالكامل تقريبًا على الخيزران ، حيث تأكل من 26 إلى 84 رطلاً في اليوم.',
      'assets/sounds/panda.mp3',
      'الباندا العملاقة لها معطف مميز بالأبيض والأسود ، مع فرو أسود حول عيونها وعلى آذانها وخطمها وأرجلها وأكتافها. يساعد معطفهم السميك والصوفي على إبقائهم دافئًا في منازلهم الجبلية الباردة. يبلغ طول الباندا البالغة حوالي 150 سم من الأنف إلى الردف ، وذيل 10-15 سم.',
      'تصل الي 20 عاماً',
      'قهقاع',
      'حيوان غير أليف'
    ],
    'animal-13': [
      'الكنغر',
      'assets/icons/Kangaroo.png',
      '18 - 100 كجم',
      '* الطول 1.5 - 2 م',
      'يعتبر الكنغر من الحيوانات العاشبة ، ويتغذى بشكل رئيسي على الأوراق والأعشاب في البرية. يتغذى الكنغر على نظام غذائي أساسي من قش البرسيم.',
      'assets/sounds/kangaroo.mp3',
      'جميع حيوانات الكنغر لها شعر قصير وأرجل خلفية قوية وأطراف أمامية صغيرة وأقدام كبيرة وذيل طويل. لديهم سمع ممتاز وبصر شديد. اعتمادًا على الأنواع ، يمكن أن يكون معطف الفرو أحمر أو رمادي أو بني فاتح إلى بني غامق. ذيلهم العضلي يستخدم للتوازن عند القفز ، وكطرف آخر عند التحرك.',
      '6 - 20 عام',
      'مثل صوت كحة الإنسان لاوجد له إسم في اللغة العربية',
      'يمكن للكنغر التواصل مع البشر على غرار الطريقة التي تتواصل بها الكلاب والخيول والماعز على الرغم من عدم تربيتهم مطلقًاً.'
    ],
    'animal-14': [
      'الكوالا',
      'assets/icons/koala.png',
      '4 - 15 كجم',
      '* الطول: 70 - 90 سم',
      'الكوالا تأكل مجموعة متنوعة من أوراق الأوكالبتوس وعدد قليل من أنواع الأشجار الأخرى ذات الصلة ، وأنواع اللحاء الورقي وأشجار الدم.',
      'assets/sounds/koala.mp3',
      'تشتهر الكوالا برأسها المستدير الكبير وآذانها الكبيرة ذات الفرو وأنفها الأسود الكبير. عادة ما يكون فرائها رماديًا بني اللون مع فرو أبيض على الصدر والذراعين الداخليين والأذنين والأسفل. ليس لديهم فرو على أنوفهم أو كفوفهم. يعاني الكوالا من ضعف في الرؤية ويعتمدون بشكل كبير على حواسهم الأخرى.',
      '13 - 18 عام',
      'خوار',
      'حيوان غير أليف'
    ],
    'animal-15': [
      'السلحفاة',
      'assets/icons/Turtle.png',
      '50 - 680 كجم',
      '* الطول: 139 إلى 160 سم',
      'تأكل السلاحف في البرية مجموعة متنوعة من الأشياء بما في ذلك الديدان والحشرات الصغيرة والقواقع والأسماك. السلاحف البرية هي آكلة اللحوم بشكل رئيسي عندما تكون صغيرة لأن أجسامها تتطلب البروتين من أجل النمو. بالإضافة إلى ذلك ، تحتاج السلاحف النامية إلى الفيتامينات والعناصر الغذائية التي يمكن العثور عليها في كبد الأسماك المغذية.',
      'assets/sounds/turtle.mp3',
      'كل السلاحف لها قشرة مستديرة أو ملساء أو شوكية. السلاحف المائية لها قشرة ناعمة ذات شكل مدبب مصمم للسباحة بكفاءة. الصدفة هي ميزة مميزة تفصل السلاحف المائية عن السلاحف البرية. تحتل السلاحف العضلية بيئات الأرض والمياه وتعمل كمفترسات كمائن.',
      '10 - 80 عام',
      'سُئل',
      'حيوان أليف'
    ],
    'animal-16': [
      'الحمار الوحشي',
      'assets/icons/zebra.png',
      '200 - 450 كجم',
      '1.3 - 1.9 م',
      'تعتبر الحمير الوحشية من الحيوانات العاشبة وتتغذى في الغالب عن طريق الرعي على الحشائش ، على الرغم من أنها قد تتصفح قليلاً على أوراق الشجيرات وسيقانها. يرعون لساعات عديدة كل يوم ، مستخدمين أسنانهم الأمامية القوية لقص أطراف العشب. ثم تقوم أسنانهم الخلفية بسحق الطعام وطحنه.',
      'assets/sounds/zebra.mp3',
      'يُعتقد عمومًا أن الحمر الوحشية تحتوي على معاطف بيضاء بخطوط سوداء أو بنية اللون ، وفقًا لحديقة حيوان سان دييغو ، لأن الخطوط تنتهي عند بطونها والجانب الداخلي من الأرجل ، وهي بيضاء ، لكل نوع من أنواع الحمار الوحشي نمط عام مختلف. من المشارب.',
      'تصل إلي 20 عاماً',
      'النهيق',
      'حيوان أليف'
    ],
    'animal-17': [
      'الخنزير',
      'assets/icons/pig.png',
      '75 - 150 كجم',
      '55 - 120 سم',
      'تأكل الخنازير أي شيء تقريبًا ، وجميع أنواع الفضلات ، أو بقايا الطعام مثل الخبز والحبوب الأخرى والخضروات والفاكهة ، ويتم الحفاظ على معدلات نموها بشكل أفضل عندما تتغذى الحيوانات على علف مصنوع خصيصًا للخنازير.',
      'assets/sounds/pig.mp3',
      'الخنازير هي ثدييات قوية الجسم ، قصيرة الأرجل ، آكلة اللحوم ، وذات جلد سميك عادة ما تكون مغطاة بقليل من الشعيرات القصيرة. خطم مسطح يمكن أن يتحرك بشكل مستقل عن رؤوسهم وعيونهم الصغيرة وآذانهم الكبيرة. إنها حيوانات اجتماعية ذكية للغاية ، وتوجد في جميع أنحاء العالم. ، حوافرها لها رقمان وظيفيان واثنان من الأرقام غير الوظيفية. نشأت الخنازير المحلية في أمريكا الشمالية من المخزونات البرية التي لا تزال موجودة في غابات أوروبا وآسيا وشمال إفريقيا.',
      '15 - 20 عام',
      'خنخنة، قُبَاع',
      'حيوان أليف',
    ],
    'animal-18': [
      'الطاووس',
      'assets/icons/Peacock.png',
      '4 - 6 كجم',
      '* الطول من الرأس حتى الذيل من 100 إلى 115 سم',
      'الطاووس من الحيوانات آكلة اللحوم مما يعني أنها ستأكل كل من النباتات واللحوم. يأكل الطاووس البري الفاكهة والتوت والحبوب والنمل وبتلات الزهور والنباتات. سوف يأكل الطاووس الأسير أيضًا طعام القطط والجبن والمكسرات والبيض المخفوق والأرز المطبوخ وفضلات المطبخ.',
      'assets/sounds/Peacock.mp3',
      'أجسادهم مغطاة بالريش البني وذيل ممدود مع ريش أزرق مخضر مثير للإعجاب تم العثور عليه عند الذكور. يشكل ذيل الطاووس 60٪ من طوله بالكامل. الذيل له بقع شبيهة بالعين مع ريش أحمر وذهبي وأخضر يحيط ببقع العين.',
      '10 - 25 عام',
      'أَصْوَاء',
      'الطاووس حيوانات أليفة شهيرة مع أناس يتوقون لاستضافة طائر الزينة المبهرج.',
    ],
    'animal-19': [
      'القنفذ',
      'assets/icons/headgehog.png',
      '00.4 - 1.2 كجم ',
      '10 - 30 سم',
      'أهم اللافقاريات في نظامها الغذائي هي الديدان ، والخنافس ، والرخويات ، واليرقات ، وحلق الأذن ، والديدان الألفية. بالإضافة إلى هؤلاء ، يأكلون أيضًا مجموعة واسعة من الحشرات الأخرى. في كثير من الأحيان ، سوف يستفيدون من الجيف والضفادع والقوارض الصغيرة والطيور الصغيرة وبيض الطيور والفاكهة الساقطة.',
      'assets/sounds/hedgehog.mp3',
      'القنافذ هي ثدييات صغيرة ذات وجوه مخروطية الشكل وأرجل قصيرة وأجسام مغطاة بريشات تشبه النيص. ريشات القنفذ مصنوعة من الكيراتين ، مثل أظافر الإنسان. وفقًا لمؤسسة الحياة البرية الأفريقية (AWF) ، يمكن أن يحتوي القنفذ على ما يصل إلى 6000 ريشة على جسمه.',
      '2 - 5 عام',
      'صمصم',
      'تتميز القنافذ الأليفة بالهدوء والنشاط والتسلية وتتطلب الكثير من العناية. إنهم يصنعون حيوانات أليفة رفيقة رائعة ، ومع ذلك ، كحيوانات ليلية ، ستحتاج إلى إطعامهم والعناية بهم في ساعات المساء.',
    ],
    'animal-20': [
      'الأرنب',
      'assets/icons/rabbit.png',
      '2 - 4.5 كجم',
      '* الطول: 20 - 50 سم',
      'القش أو العشب الجيد ، المتوفر دائمًا ، يشكل غالبية وجبات الأرانب. ترعى الأرانب وتتغذى بشكل طبيعي على العشب والنباتات الأخرى لفترات طويلة ، خاصة عند الفجر والغسق. تحتاج الأجهزة الهضمية للأرانب إلى العشب أو القش لتعمل بشكل صحيح.',
      'assets/sounds/rabbit.mp3',
      'الأرانب ثدييات صغيرة ذات فراء وذات أذنين طويلتين وذيول قصيرة منفوشة وأرجل خلفية قوية وكبيرة. لديهم زوجان من القواطع الحادة (الأسنان الأمامية) ، زوج واحد في الأعلى وزوج في الأسفل. لديهم أيضًا 2 من أسنان الوتد خلف القواطع العلوية.',
      'هناك أكثر من 30 نوعًا حول العالم ، وبينما يعيشون في العديد من البيئات المختلفة ، لديهم العديد من الأشياء المشتركة. تنتمي الأرانب والأرانب البرية إلى نفس العائلة التصنيفية ، لكنها تنتمي إلى أجناس مختلفة.',
      'يمكن أن يعيش بسهولة حتى يبلغ من العمر 8 أعوام',
      'ضغيب',
      'حيوان أليف وجميل جداً'
    ],
    'animal-21': [
      'الحصان',
      'assets/icons/horse.png',
      '380 - 1000 كجم',
      '1.4 - 1.8 م',
      'تأكل الخيول العشب والتبن أو البرد ، لكن الملح والمركزات والفواكه أو الخضار يمكن أن تعزز أيضًا نظامهم الغذائي ، اعتمادًا على نظام العمل المطلوب والأعلاف المتاحة.',
      'assets/sounds/horse.mp3',
      'للخيول حوافر بيضاوية الشكل وذيل طويل وشعر قصير وأرجل طويلة نحيلة وجذع عضلي وعميق وأعناق طويلة وسميكة ورؤوس ممدودة كبيرة. عرف الرجل هو منطقة من الشعر الخشن ، والتي تمتد على طول الجانب الظهري من الرقبة في كل من الأنواع الداجنة والبرية ، ويمكن للخيول إظهار سمات تجعلها اجتماعية ، منعزلة ، خائفة ، وصعبة. علاوة على ذلك ، بالإضافة إلى ملاحظة سمات مزاجية معينة تتناسب مع خيولك بشكل أفضل ، تحتاج أيضًا إلى ملاحظة كيف يظهر الحصان "بصوت عالٍ" أو "بهدوء" ("عدواني" أو "سلبي") شخصيته.',
      '25 - 30 عام',
      'صهيل',
      'حيوان أليف وجميل',
    ],
    'animal-22': [
      'الجمل',
      'assets/icons/camel.png',
      '400 - 600 كجم',
      '1.8 - 2 م',
      'في الصحراء ، يطعم الناس الجمال بالعشب والحبوب والقمح والشوفان. عندما تسافر الجمال في الصحراء ، غالبًا ما يصعب العثور على الطعام. لذلك قد يضطر الحيوان إلى العيش على أوراق الشجر الجافة والبذور والأغصان الشائكة (دون الإضرار بأفواههم).',
      'assets/sounds/camel.mp3',
      'الأرجل الطويلة والرأس الصغير تجعل الجمل تبدو بشكل غريب. تبدو مشيته أيضًا محرجة حيث تتحرك الأرجل الأمامية والخلفية على نفس الجانب للأمام معًا ، مما يخلق حركة هزازة. الجمال إما سنام واحد أو سنامين.',
      'تصل إلي 40 عام ',
      'هدير',
      'حيوان أليف'
    ],
    'animal-23': [
      'الكلب',
      'assets/icons/jermandog.png',
      '30 - 40 كجم',
      '15 - 110 سم',
      'طعام جاف',
      'assets/sounds/dog.mp3',
      'الكلاب من الثدييات المستأنسة وليست حيوانات برية طبيعية. تم تربيتها في الأصل من الذئاب. لقد تم تربيتها من قبل البشر لفترة طويلة ، وكانت أول الحيوانات التي يتم تدجينها على الإطلاق. إنها حيوانات أليفة شائعة لأنها عادة ما تكون مرحة وودودة ومخلصة وتستمع إلى البشر. يشار إلى الكلاب أحيانًا على أنها أفضل صديق للإنسان لأنها تُحتفظ بها كحيوانات أليفة منزلية وعادة ما تكون مخلصة وتحب أن تكون حول البشر. تحب الكلاب أن يتم تربيتها ، ولكن فقط عندما يتمكنوا من رؤية اليد أولاً قبل الملاعبة ، يجب ألا يداعب المرء كلبًا من الخلف أبدًا.',
      '10 - 13 عاماً',
      'نباح',
      'حيوان أليف ، أفضل صديق للإنسان.',
    ],
    'animal-24': [
      'القطة',
      'assets/icons/cat.png',
      '3.6 - 4.5 كجم',
      '23 - 25 سم',
      'القطط من أكلة اللحوم ، يجب أن يكون لديهم بروتين من اللحوم لقلب قوي ، ورؤية جيدة ، وجهاز تناسلي صحي. يعد لحم البقر والدجاج والديك الرومي المطبوخ وكميات صغيرة من اللحوم قليلة الدهن طريقة رائعة لمنحهم ذلك. اللحوم النيئة أو الفاسدة يمكن أن تجعل قطتك مريضة.',
      'assets/sounds/cat.mp3',
      'القط حيوان فروي له ذيل طويل ومخالب حادة. غالبًا ما يتم الاحتفاظ بالقطط كحيوانات أليفة. القطط هي الأسود والنمور والحيوانات البرية الأخرى في نفس العائلة.',
      '2 - 16 عام',
      'مواء',
      'حيوان أليف',
    ],
    'animal-25': [
      'فرس النهر',
      'assets/icons/Hippopotamus.png',
      'الذكور: 1500 - 1800 كجم ، الإناث: 1300 - 1500 كجم',
      '1.5 م',
      'يقضون أربع إلى خمس ساعات في الرعي ويمكن أن يستهلكوا 68 كجم من العشب كل ليلة. مثل معظم الحيوانات العاشبة ، تستهلك أفراس النهر نباتات أخرى إذا قدمت معها ، لكن نظامها الغذائي في الطبيعة يتكون بالكامل تقريبًا من العشب ، مع استهلاك ضئيل فقط من النباتات المائية.',
      'assets/sounds/hippo.mp3',
      'أفراس النهر هي ثدييات كبيرة شبه مائية ، لها جسم كبير على شكل برميل ، وأرجل قصيرة ، وذيل قصير ورأس ضخم! لديهم بشرة رمادية إلى بنية موحلة ، والتي تتلاشى إلى اللون الوردي الباهت تحتها. تم العثور على هذه الثدييات الرائعة مرة واحدة في جميع أنحاء أفريقيا جنوب الصحراء الكبرى.',
      '40 - 50 عام',
      'قباع',
      'إن أفراس النهر عدوانية وتعتبر خطيرة للغاية. لديهم أسنان وأنياب كبيرة يستخدمونها لصد التهديدات ، بما في ذلك البشر. في بعض الأحيان ، يقع صغارهم ضحية لأفراس النهر البالغة. أثناء القتال بين شخصين بالغين ، يمكن أن يصاب فرس النهر الصغير الذي يقع في المنتصف بجروح خطيرة أو حتى يتم سحقه.'
    ],
    'animal-26': [
      'الثور',
      'assets/icons/ox.png',
      '350 - 1000 كجم',
      '1.2 م',
      'الثيران من الحيوانات العاشبة ، مما يعني أنها تأكل نظامًا غذائيًا من النباتات والحبوب. تأكل الثيران المستأنسة الأعشاب الطازجة بالإضافة إلى مكملات التبن والحبوب.',
      'assets/sounds/oxen.mp3',
      'الثور بني غامق أو أسود. لديهم شعر خارجي طويل وخشن مما يجعلها تبدو مثل الجاموس لكنها في الواقع تشبه الأغنام.',
      '18 - 22 عام',
      'خوار',
      'حيوان غير أليف'
    ],
    'animal-27': [
      'الجاموس',
      'assets/icons/bufflo.png',
      '425 - 870 كجم',
      '1 - 1.7 متر',
      'الجاموس من الحيوانات العاشبة ، لذلك لا تأكل سوى النباتات. طعامهم المفضل هو العشب والأعشاب ، لكن جاموس الماء يأكل أيضًا النباتات المائية. يأكل الجاموس الأفريقي والآسيوي الشجيرات والأشجار عندما لا يجدون الحشائش أو الأعشاب ليأكلوها.',
      'assets/sounds/buffalo.mp3',
      'يمكن أن يبلغ طول الجاموس من 6 إلى 7 أقدام ، ويقف من 5 إلى 6 أقدام ويصل وزنه إلى 2000 رطل. حجمها يجعلها أكبر حيوان يعيش في أمريكا الشمالية. ... الجاموس من الحيوانات العاشبة ويتغذى على حوالي 60 رطلاً من المواد النباتية والأعشاب يوميًا. يعتبر الجاموس بالغًا عندما يبلغ من العمر 3 سنوات.',
      'حوالي 26 عام',
      'الخُوار',
      'حيوان أليف',
    ],
    'animal-28': [
      'الخروف',
      'assets/icons/Sheep.png',
      '45 - 160 كجم',
      '82 - 140 سم',
      'الأغنام من الحيوانات العاشبة وتتغذى بشكل أساسي على المواد النباتية. في البرية أو عند العيش في المراعي ، تقضي الأغنام جزءًا كبيرًا من يومها في الرعي على العشب والأعشاب الضارة. غالبًا ما يتم تغذية الأغنام التي تعيش في حظيرة بدون عشب لرعيها على التبن أو العلف أو الذرة.',
      'assets/sounds/sheep.mp3',
      'الأغنام هي ثدييات ذات أربع أرجل من الأصابع أو حتى أصابع القدم (لها إصبعان في كل إصبع). الأغنام مغطاة بالكامل تقريبًا بالصوف. الصوف عبارة عن شعر ناعم مجعد يستخدم للألياف ، وهو مهيج جدًا للجلد عندما يكون في شكل سترة. الأغنام لها قرون تشكل دوامة جانبية. سمة أخرى تنفرد بها الأغنام هي اختلاف لونها الواسع.',
      '10 - 12 عام',
      'مأمأة',
      'حيوان أليف',
    ],
    'animal-29': [
      'الماعز',
      'assets/icons/goat.png',
      '20 - 140 كجم',
      '41 -58 سم',
      '90٪ من الطعام الذي يأكلونه عبارة عن مرعى أو تبن. مما لا شك فيه أن هذا هو الأكثر تفضيلاً. بشكل عام ، تحب الماعز أكل المراعي والزبيب والخضر والبذور وبذور عباد الشمس والجزر وبذور اليقطين.',
      'assets/sounds/goat.mp3',
      'الماعز ، من الثدييات أجوف القرون التي تنتمي إلى جنس كابرا. بالنسبة للخراف ، فإن الماعز أخف في البناء ، ولها قرون تتقوس إلى الوراء ، وذيل قصير ، وشعر أكثر استقامة. عادة ما يكون لديهم لحية.',
      '15 - 18 عام',
      'ثغاء',
      'حيوان أليف',
    ],
    'animal-30': [
      'البطة',
      'assets/icons/duck.png',
      '1 - 8 كجم',
      '10 - 60 سم',
      'وجبة البرسيم (عالية البروتين ، جيدة للشتاء) ، الذرة (الدعامة الأساسية للدجاج ، تخزن كاملة) ، البازلاء (للبروتين ، لتجنب استخدام فول الصويا) ، القمح ، الشوفان أو الشعير.',
      'assets/sounds/duch.mp3',
      'البط في الغالب من الطيور المائية ، ومعظمها أصغر من البجع والأوز ، ويمكن العثور عليها في كل من المياه العذبة ومياه البحر. أحيانًا يتم الخلط بين البط وأنواع عديدة من الطيور المائية التي لا علاقة لها بأشكال متشابهة ، مثل الصقور أو الغواصين ، والجريبس ، والجلينول ، والقطرات.',
      '2 - 10 أعوام',
      'البطبطة',
      'حيوان أليف',
    ],
    'animal-31': [
      'الدجاج',
      'assets/icons/chicken.png',
      '1 - 5 كجم',
      '10 - 40 سم',
      'وجبة البرسيم (عالية البروتين ، جيدة للشتاء) ، الذرة (الدعامة الأساسية للدجاج ، تخزن كاملة) ، البازلاء (للبروتين ، لتجنب استخدام فول الصويا) ، القمح ، الشوفان أو الشعير.',
      'assets/sounds/chichen.mp3',
      'الدجاجة طائر. من الميزات التي تميزه عن معظم الطيور الأخرى أنه يحتوي على مشط ودويتين. المشط هو الملحق الأحمر في أعلى الرأس ، والدويتان هما الملحقان الموجودان أسفل الذقن. هذه خصائص جنسية ثانوية وهي أكثر بروزًا عند الذكور. بعض الطيور الأخرى لديها مشط أو ملحق مشابه ، وفي بعض الحالات تحمل اسمًا مختلفًا مثل خوذة في غينيا ، وقليل منها لديها دلايات وبعضها يمتلك واحدًا متوسطًا واحدًا بدلاً من زوج.',
      '2 - 10 أعوام',
      'نقنقة ',
      'حيوان أليف',
    ],
    'animal-32': [
      'الضفدعة',
      'assets/icons/frog.png',
      '22.7 جم',
      '* طولها 4.2 - 15 سم',
      'تتغذى الضفادع الصغيرة على الحشرات مثل الذباب والعث ، وكذلك القواقع والبزاقات والديدان. يستخدمون ألسنة طويلة ولعابًا لزجًا لاصطياد الفريسة التي تمر بهم. تأكل الضفادع الصغيرة الطحالب في البرك التي تنمو فيها. وأثناء نموها ، تتغذى على النباتات والحشرات الصغيرة. إذا لم يكن هناك ما يكفي من الطعام المتاح ، فقد يأكلون حتى الضفادع الصغيرة.',
      'assets/sounds/frog.mp3',
      'الضفادع من البرمائيات المعروفة بقدراتها على القفز وأصوات النعيق وانتفاخ العينين والجلد اللزج. إنهم يعيشون في جميع أنحاء العالم وهم من بين أكثر الحيوانات تنوعًا في العالم ، مع أكثر من 6000 نوع. يفوق عدد الضفادع بشكل كبير المجموعتين الأخريين من البرمائيات - السلمندر والديدان الثعبانية.',
      '10- 12 عام',
      'نقيق',
      'الضفادع ليست حيوانًا أليفًا يجب التعامل معها بانتظام نظرًا لبشرتها الخاصة والحساسة.',
    ],
    'animal-33': [
      'الببغاء',
      'assets/icons/parrot.png',
      '64 جم - 1.6 كجم',
      '8.7 - 100 سم',
      'أفضل الأطعمة التي يأكلها الببغاء هي الخضروات الطازجة والفواكه والحبيبات أو البذور. في البرية ، يمكن أن يختلف نظام الببغاء الغذائي بشكل كبير ويحبون تناول الفاكهة وبذور الفاكهة والمكسرات والزهور والذرة حيث يمكنهم العثور عليها.',
      'assets/sounds/parrot.mp3',
      'الببغاوات لها وزن ثقيل بالنسبة لحجمها وجسم مضغوط مع رأس كبير وعنق قصير. مناقيرهم قصيرة وقوية ومنحنية. جزأا المنقار قويتان للغاية ويستخدمان لكسر الثمار والبذور. العديد من الببغاوات ملونة بشكل واضح ، وبعضها متعدد الألوان ، ولديها أربعة أصابع في كل قدم ، اثنان يشيران إلى الأمام واثنان يتجهان للخلف. معظم الببغاوات تأكل الفاكهة والزهور والبراعم والمكسرات والبذور.',
      '40 - 80 عاماً',
      'نقيق',
      'حيوان أليف وجميل جداً'
    ],
    'animal-34': [
      'الفراشة',
      'assets/icons/butterfly.png',
      'أقل من جرام',
      '* الطول من 2 - 10 سم',
      'تشرب معظم الفراشات رحيق الأزهار من خلال ألسنتها ، والتي تعمل مثل القش. أقلية من الفراشات لا تزور الزهور أبدًا ، وبدلاً من ذلك تحصل على قوتها من عصارة الأشجار ، والمواد الحيوانية المتعفنة ، والمواد العضوية الأخرى.',
      'assets/sounds/butterfly.mp3',
      'الفراشة البالغة لها أربعة أجنحة مغطاة بمقاييس دقيقة تمنحها تصاميم ملونة ومتنوعة. لديهم ستة أرجل ، واثنين من الهوائيات ، ورأس ، وعيون مركبة ، وصدر ، وبطن. تتمتع الفراشات أيضًا ببصر جيد إلى حد ما.',
      'تصل إلى 12 شهرًا',
      'تكسير بصوت عال',
      'طائر أليف وجميل جداً'
    ],
    'animal-35': [
      'النسر',
      'assets/icons/eagle.png',
      '3 - 6.3 كجم',
      'يبلغ طول الذكر البالغ حوالي 90 سم ويبلغ طول جناحيه مترين. الإناث ، التي تنمو أكبر إلى حد ما من الذكور ، قد يصل طولها إلى 108 سم ولها جناحيها 2.5 متر.',
      'يأكلون فريسة حية تتكون من ثدييات وطيور متوسطة الحجم مثل الأرانب.',
      'assets/sounds/eagle.mp3',
      'النسور هي طيور جارحة كبيرة الحجم وذات بناء قوي ولها رؤوس ومناقير ثقيلة. مثل جميع الطيور الجارحة ، تمتلك النسور مناقير معقوفة كبيرة جدًا لتمزيق اللحم من فرائسها وأرجلها القوية والعضلية ومخالبها القوية. عادة ما يكون المنقار أثقل من معظم الطيور الجارحة الأخرى.',
      '20 - 31 عام',
      'صفير',
      'يمكن تربية النسور. ومع ذلك ، هناك أنواع معينة من النسور يمكن تدريبها ، مثل النسر الذهبي. من بين جميع الحيوانات التي ربتها البشرية في التاريخ ، قد تكون النسور الذهبية هي أكثر الأنواع البرية والأكثر إثارة على الإطلاق.'
    ],
    'animal-36': [
      'الحمامة',
      'assets/icons/Pigeon.png',
      '240 - 380 جم',
      '25 - 30 سم',
      'يأكل الحمام الذي يهيمن على مدننا وبيئاتنا الحضرية أي شيء تقريبًا ، من الحشرات إلى بقايا الطعام التي نتخلص منها. يأكل الحمام البري كل ما ترمي به الطبيعة. مرة أخرى ، هذا يشمل الحشرات مثل الديدان والنمل ، وكذلك البذور والفواكه والتوت والخضروات.',
      'assets/sounds/pigeons.mp3',
      'رأس وعنق وصدر رمادى مزرق داكن مع تقزح أخضر لامع وأرجواني محمر حول العنق وريش الجناح. 2 شريط أسود في الجناح ، ورأس أزرق رمادي. طائر ممتلئ الجسم بأرجل قصيرة ورأس صغير. الريش متغير. بعض الطيور رمادية داكنة مع تقزح أخضر أرجواني على الرقبة. قزحية برتقالية أو حمراء مع حلقة داخلية شاحبة (للبالغين) أو بني أو بني رمادي (الأحداث) منقار أسود مع قير أبيض مصفر. احمرار القدمين والساقين.',
      '2 - 3 أعوام',
      'هديل',
      'طائر أليف',
    ],
    'animal-37': [
      'الغراب',
      'assets/icons/crow.png',
      '337 - 1.625 جم',
      '45 - 48 سم',
      'الغربان من الحيوانات آكلة اللحوم ، مما يعني أنها تأكل أي شيء تقريبًا. تأكل الغربان الحيوانات الصغيرة مثل الثدييات والبرمائيات والزواحف والبيض والجيف. كما يأكلون الحشرات والبذور والحبوب والمكسرات والفواكه والمفصليات غير الحشرية والرخويات والديدان وحتى الطيور الأخرى.',
      'assets/sounds/crow.mp3',
      'الغربان هي طيور كبيرة ذات سيقان طويلة ومنقار ثقيل ومستقيم. هذه الطيور سوداء اللون بالكامل ، بما في ذلك أرجلها وأقدامها. لديهم ريش مميز على ظهرهم العلوي بجودة براق ، والتي تظهر بشكل خاص في ضوء الشمس.',
      '7 - 15 عام',
      'نعيق',
      'طائر غير أليف',
    ],
    'animal-38': [
      'النحلة',
      'assets/icons/bee.png',
      '0.8 جرام',
      '18 ملليمتر',
      'يستخدم معظم النحل حبوب اللقاح والرحيق كمصدر للغذاء.',
      'assets/sounds/bee.mp3',
      'النحل له لسان طويل يشبه القش يسمى بروبيسكوس الذي يسمح له بشرب الرحيق من أعماق الأزهار. تم تجهيز النحل أيضًا بجناحين ، وهوائيين ، وثلاثة أجزاء من الجسم (الرأس والصدر والبطن). نحل العسل حشرات اجتماعية تعيش في مستعمرات.',
      'خلال الموسم النشط ، يكون عمر العامل من خمسة إلى ستة أسابيع. ومع ذلك ، قد يعيش النحل العامل في الشتاء لمدة أربعة إلى ستة أشهر.',
      'طنين',
      'حيوان غير أليف',
    ],
    'animal-39': [
      'البومة',
      'assets/icons/owl.png',
      'تقريباً تصل إلي 4.5 كجم',
      '43 - 64 سم',
      'تتغذى البوم على الحيوانات الأخرى ، من الحشرات الصغيرة مثل العث أو الخنافس.',
      'assets/sounds/owl.mp3',
      'سواء كانت كبيرة أو صغيرة ، فكلها تبدو ممتلئة الجسم برؤوس كبيرة وريش ناعم. تميل ألوان ريش البومة إلى البني والبني والرمادي والحمري والأبيض. لها نغمات صامتة تساعد البوم على التمويه ضد جذوع الأشجار وفروعها. على عكس معظم الطيور الجارحة ، فإن العديد من البوم لديها ريش على أرجلها وأصابعها.',
      '20 - 25 عام',
      'نعيق',
      'طائر غير أليف وغير مستحب',
    ],
    'animal-40': [
      'الثعبان',
      'assets/icons/snake.png',
      '1 - 75 كجم',
      '* الطول: 0.3 - 15 م',
      'جميع الثعابين من الحيوانات آكلة اللحوم. نظامهم الغذائي يعتمد على الأنواع. يأكل البعض فريسة ذوات الدم الحار (مثل القوارض والأرانب والطيور) ، بينما يأكل البعض الآخر الحشرات والبرمائيات (الضفادع) والبيض والزواحف الأخرى والأسماك وديدان الأرض أو الرخويات ، تبتلع الأفاعي طعامها بالكامل.',
      'assets/sounds/snake.mp3',
      'الثعبان هو زاحف له جسم طويل نحيف ولكن بدون أرجل. بعض السحالي عديمة الأرجل وتبدو مثل الثعابين ، ومعظم السحالي لها جفون ، وفك الثعبان مرنان ويمكنهما الفتح على نطاق واسع ، لذا يمكن للثعابين التعامل مع الفريسة الكبيرة. أكثر من 3400 نوع من الزواحف تتميز بحالة عدم وجود أطراف لها وجسمها وذيلها الممدودان بشكل كبير. جميع الثعابين تفتقر إلى أطراف خارجية.',
      '9 - 30 عام',
      'فحيح',
      'خطير للغاية، حيوان غير أليف',
    ],
  };

  changeLan(bool lan) async {
    isEn = lan;
    notifyListeners();
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool("isEn", isEn);
  }

  getLan() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    isEn = prefs.getBool("isEn") ?? true;
    notifyListeners();
  }

  Object? getTexts(String txt) {
    if (isEn == true) return textsEn[txt];
    return textsAr[txt];
  }
}
